# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6tRAN8-o3dLujHJmM177q8wc9RcyzmO
"""

driven=int(input("enter the number of drive gear teeth:"))
driver=int(input("enter the number of driver gear teeth:"))
gearratio=driven/driver
print("gear ratio:",gearratio)
drivenspeed=int(input("enter speed of driven gear:"))
driverspeed=int(input("enter the speed of driver gear:"))
speed=drivenspeed/driverspeed
print("gearratio",speed,"RPM")
torque=int(input("enter input torque:"))
outputtorque=gearratio*torque
print("torque of gear is:",outputtorque,"Nm")
inputtorque=float(input("enter input torque Nm:"))
efficiency=outputtorque/inputtorque*100
print("efficiency of gear is:",efficiency,"%")
import matplotlib.pyplot as plt
x = [750,100]
y = [51,12]
plt.plot(x, y, marker='o', linestyle='-', color='b', label='Prime Numbers')
plt.title('SPEED VS TORQUE')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend()
plt.grid(True)
plt.show()